title = 'aorlnn'
baseURL = 'https://aorlnn.xyz/'
languageCode = 'en-us'
theme = 'ananke'

DefaultContentLanguage = "en"
enableRobotsTXT = true

copyright = 'aorlnn.xyz'
disablePathToLower = true
enableEmoji = true
enableGitInfo = true

[params]
background_color_class = "bg-black"
recent_posts_number = 3

[services]
[services.googleAnalytics]
ID = 'G-TYPWLJMT9L'